apiVersion: v1
baseDomain: ipi.testing
compute:
- name: worker
  replicas: 3
controlPlane:
  name: master
  replicas: 3
  platform:
    baremetal: {}
metadata:
  name: goblin
networking:
  clusterNetworks:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  baremetal:
    apiVIP: 10.0.1.5
    ingressVIP: 10.0.1.4
    dnsVIP: 10.0.1.3
    provisioningBridge: provisioning
    externalBridge: baremetal
    hosts:
      - name: master-0
        role: master
        bmc:
          address: ipmi://10.19.110.2
          username: ADMIN
          password: ADMIN
        bootMACAddress: 0c:c4:7a:db:a8:55
        hardwareProfile: default

      - name: master-1
        role: master
        bmc:
          address: ipmi://10.19.110.12
          username: ADMIN
          password: ADMIN
        bootMACAddress: 0C:C4:7A:DB:A9:93
        hardwareProfile: default

      - name: master-2
        role: master
        bmc: 
          address: ipmi://10.19.110.10
          username: ADMIN
          password: ADMIN
        bootMACAddress: 0C:C4:7A:DB:A8:59
        hardwareProfile: default
    
      - name: worker-0
        role: worker
        bmc:
          address: ipmi://10.19.110.8
          username: ADMIN
          password: ADMIN
        bootMACAddress: 0C:C4:7A:DB:AC:03
        hardwareProfile: default

      - name: worker-1
        role: worker
        bmc:
          address: ipmi://10.19.110.22
          username: ADMIN
          password: ADMIN
        bootMACAddress: 0c:c4:7a:db:a9:b3
        hardwareProfile: default

      - name: worker-2
        role: worker
        bmc:
          address: ipmi://10.19.110.20
          username: ADMIN
          password: ADMIN
        bootMACAddress: 0c:c4:7a:db:a9:b1
        hardwareProfile: default

pullSecret: 'PULL_SECRET'
sshKey: |
   SSH_PUB_KEY
