apiVersion: v1
baseDomain: ipi.testing
compute:
- name: worker
  replicas: 3
controlPlane:
  name: master
  replicas: 3
  platform:
    baremetal: {}
metadata:
  name: goblin
networking:
  clusterNetworks:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  baremetal:
    apiVIP: 192.168.111.5
    ingressVIP: 192.168.111.4
    dnsVIP: 192.168.111.3
    provisioningBridge: provisioning
    externalBridge: baremetal
    hosts:
        # Master nodes are always RHCOS
        - name: master-0
          role: master
          bmc:
            address: ipmi://10.19.110.2
            credentialsName: ha-lab-ipmi
          bootMACAddress: 0c:c4:7a:db:a8:55  # provisioning network mac
          sdnMacAddress: 0c:c4:7a:19:6f:84   # baremetal network mac
          # sdnIPAddress: 192.168.111.11     # Optional -- Set static IP
          hardwareProfile: default

        - name: master-1
          role: master
          bmc:
            address: ipmi://10.19.110.12
            credentialsName: ha-lab-ipmi
          bootMACAddress: 0C:C4:7A:DB:A9:93  # provisioning network mac
          sdnMacAddress: 0c:c4:7a:19:6f:92   # baremetal network mac
          # sdnIPAddress: 192.168.111.11     # Optional -- Set static IP
          hardwareProfile: default
          osProfile: 
              # With role == master, the osType is always rhcos
              # And with type rhcos, the following are settings are available
              pxe: bios         # pxe boot type either bios (default if not specified) or uefi
              install_dev: sda  # where to install the operating system (sda is the default)

        - name: master-2
          role: master
          bmc: 
            address: ipmi://10.19.110.10
            credentialsName: ha-lab-ipmi
          bootMACAddress: 0C:C4:7A:DB:A8:59
          sdnMacAddress: 0c:c4:7a:19:70:cc
          hardwareProfile: default
          # If an osProfile/type is not defined, rhe node defaults to RHCOS
          # osProfile: 
              # type: rhcos
              # With type: rhcos the following are settings are available
              # pxe: bios|uefi    # pxe boot type either bios (default if not specified) or uefi
              # install_dev: sda  # where to install the operating system (sda is the default)
        
        # Worker nodes can be either rhcos (default) || centos (7.x) || rhel (8.x)
        - name: worker-0
          role: worker
          bmc:
            address: ipmi://10.19.110.8
            credentialsName: ha-lab-ipmi
          bootMACAddress: 0C:C4:7A:DB:AC:03
          sdnMacAddress: 0c:c4:7a:19:6f:7e
          hardwareProfile: default

        - name: worker-1
          role: worker
          bmc:
            address: ipmi://10.19.110.22
            credentialsName: ha-lab-ipmi
          bootMACAddress: 0c:c4:7a:db:a9:b3
          sdnMacAddress: 0c:c4:7a:8e:ed:ec
          hardwareProfile: default

        - name: worker-2
          role: worker
          bmc:
            address: ipmi://10.19.110.20
            credentialsName: ha-lab-ipmi
          bootMACAddress: 0c:c4:7a:db:a9:b1
          sdnMacAddress: 0c:c4:7a:8e:ed:f8
          hardwareProfile: default

pullSecret: 'PULL_SECRET'
sshKey: |
   SSH_PUB_KEY