---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 99-ifcfg-ens1f0-master
spec:
  config:
    ignition:
      version: 2.2.0
    storage: 
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,REVWSUNFPWVuczFmMApCT09UUFJPVE89ZGhjcApPTkJPT1Q9eWVzClRZUEU9RXRoZXJuZXQKSVBWNklOSVQ9bm8KREVGUk9VVEU9eWVzCg==
        filesystem: root
        mode: 0644
        path: /etc/sysconfig/network-scripts/ifcfg-ens1f0
